const RecursiveHash = require('recursive-hash');
const process = require('process');

const hashOne = (path, name, hash) => {
  const shortPath = path.replace(/\\/g, "/").split('/public').pop();
  console.log(`  "${shortPath}": "${hash.replace(/\\/g, "")}",`);
}

console.log(`{
  "NOTE": "This file is generated by scripts/make_hashes.js. Do not edit it manually.",`);
RecursiveHash.search({
  path: './public',
  processHash: hashOne,
  hashCommand: 'sha1sum'
})
  .then(() => {
    console.log('  "ZZZ": ""');
    console.log('}');
  })
  .catch(error => {
    console.log(`Error: ${error}`);
    process.exit(1);
  });
