export const FADE_TEXT_RATE: number = 1 / 60.0; // fades alpha by this amount each frame
export const DAMAGE_FONT_SIZE: number = 25;
export const DAMAGE_FONT: string = "Consolas";
export const DAMAGE_RECEIVED_COLOR: string = "#dc143c"; // crimson
export const DAMAGE_BLOCKED_COLOR: string = "#bec2cb"; // grey
export const DAMAGE_X_OFFSET_PX: number = 20; // offsets from the center of the 
export const DAMAGE_Y_OFFSET_PX: number = 0;  //   sprite in px
export const DEFAULT_FONT_SIZE: number = 12;
export const DEFAULT_FONT: string = "Consolas";
export const DEFAULT_FONT_COLOR: string = "#000000"; // black
export const TILEWIDTH: number = 64;
export const TILEHEIGHT: number = 64;
export const NUM_ENEMIES: number = 3;
export const VIEWPORT_WIDTH: number = TILEWIDTH * 22;
export const VIEWPORT_HEIGHT: number = TILEHEIGHT * 12;
export const TURNS_REMAINING_FONT_SIZE_STRING: string = "40px";
export const TURNS_REMAINING_FONT_FAMILY: string = "source serif pro";
export const TURNS_REMAINING_TEXT: string = "TURNS REMAINING:";
export const CONNECT_PROMPT_TEXT: string = "please play offline (click the X to the left), or connect a wallet\nand avatar by clicking on the glowing button above to continue!";
export const BLOCK_CONFIRMS: number = 5;
export const GAME_COST_ETHER: number = 0.001;
export const MINT_COST_ETHER: number = 0.001;
export const INPUT = Object.freeze({ UP: 1, RIGHT: 2, DOWN: 3, LEFT: 4, SPACE: 5, NONE: 6 });
export const GAME_ALREADY_STARTED_ERROR_MESSAGE = "Player already in game";